### ISSUE TITLE
Test discovery with implicit namespace packages

### ISSUE THREAD

**Issue by paparomeo** [zopefoundation/zope.testrunner#11]
Python 3.3 introduced implicit namespace packages ([PEP 420](http://www.python.org/dev/peps/pep-0420/)). Test discovery won't work for modules in packages which in turn are in an implicit namespace package.

**Comment by dataflake** [comment]
Please follow up on #160 which has more details, closing this as duplicate

**Comment by icemac** [comment]
Wow, we actually know about this problem for 10 years! Eventually the time to fix it has come.
