### ISSUE TITLE
`package init file missing` warning when running tox4

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/zope.testrunner#112]
tox gets currently rewritten and the release of the new version was announced as May 2021.

I ran the pre-release [on all Zope and Plone repositories](https://jugmac00.github.io/blog/testing-the-tox-4-pre-release-at-scale/) and found a couple of issues.

I get the following warning when I run the tox pre-release for this repository

`package init file 'src/zope/testrunner/tests/testrunner-ex/__init__.py' not found (or not a regular file)`

Having a look at both the project's  `setup.py`

```
    packages=[
        "zope",
        "zope.testrunner",
        "zope.testrunner.tests.testrunner-ex",
    ],
```

and directory, well, the directory gets declared as package but there is no `__init.py__`.

https://docs.python.org/3/distutils/setupscript.html#listing-whole-packages

The * fix*  should be to add the missing `__init__.py` file.

I am still curious why the new tox version uncovers this issue, and it was hidden in tox 3.

**Comment by mgedmin** [comment]
Should testrunner-ex even be listed in setup.py as a package?  There are plenty of sibling testunner-ex-* subdirectories that are not listed.

That directory doesn't contain any zope.testrunner code, but rather test fixtures for zope.testrunner's test suite.

It was added to setup.py in commit bd368fc for reasons I don't understand.

**Comment by jamadden** [comment]
Alternately, would it hurt to just use `packages=find_packages('src')`? We have a hard dependency on `setuptools` in `setup.py`.

**Comment by mgedmin** [comment]
It just occurred to me that `testrunner-ex` is not a syntactically valid Python package name (you can't `import testrunner-ex`), so I'm definitely -1 on adding an `__init__.py` inside.

**Comment by mgedmin** [comment]
> I am still curious why the new tox version uncovers this issue, and it was hidden in tox 3.

I think tox used to hide _all_ build warnings.  I definitely remember that testrunner-ex missing `__init__.py` warning scroll by when I ran various buildouts using zope.testrunner.

**Comment by jugmac00** [comment]
Thanks, both of you, for taking your time to have a look at this minor issue.

I now removed `testrunner-ex` from the packages-list in setup.py (and I removed the previously added `__init__.py`.
