### ISSUE TITLE
random.shuffle(random=...) is deprecated in 3.9

### ISSUE THREAD

**Issue by cjwatson** [zopefoundation/zope.testrunner#119]
Python 3.9 test runs (e.g. https://github.com/zopefoundation/zope.testrunner/runs/2129207371) show a number of instances of this:

```
/home/runner/work/zope.testrunner/zope.testrunner/src/zope/testrunner/shuffle.py:56: DeprecationWarning: The *random* parameter to shuffle() has been deprecated
since Python 3.9 and will be removed in a subsequent version.
  rng.shuffle(tests, random=rng.random)
```

See commit b7e1944cb3 for some of the history here.  Maybe we just need to inline the relevant code from `random.shuffle` or something?

**Comment by mgedmin** [comment]
Yeah, if Python doesn't provide any shuffling stability guarantees that we want, then using our own shuffling function seems best.

I don't know that we care about shuffling stability across platforms/Python versions for anything except zope.testrunner's own test suite, but I suspect that solving it generally may be easier than finding a workaround just for the test suite.
