### ISSUE TITLE
Generate XML reports

### ISSUE THREAD

**Issue by gforcada** [zopefoundation/zope.testrunner#148]
## FEATURE REQUEST

`collective.xmltestreport` is a package that wraps `zope.testrunner` that mostly adds an `--xml` option to the test runner and produces XML reports of the tests being run.

Unfortunately `collective.xmltestreport` is only usable via `zc.buildout` and it is hardly maintained, although it is stable.

Getting the XML report code merged here would be great as this would mean:

- one less dependency
- being able to have XML reports without having to depend on `zc.buildout` (again less dependencies)
- being able to easily use CI facilities that use such XML files like Jenkins, GitLab, I guess GitHub can use them, I haven't checked it but it probably can 🤷🏾

**Comment by icemac** [comment]
The idea sounds interesting.

`collective.xmltestreport` is also licensed under ZPL, so it should be no problem to move the needed code here. The only issue I see is that `collective.xmltestreport` has no tests at all. So new tests have to be written or some of the existing tests adapted to test their XML output.

**Comment by gforcada** [comment]
Cool, I did not thought of the license 😅 but the tests problem I did know.

Fortunately, given that `zope.testrunner` has some tests already, with the infrastructure ready, it should not be too much burden to write some tests 🚀

**Comment by gforcada** [comment]
Thanks for the review and merge! 😄 

Could we get a release? 🙏🏾 I want to start testing this on our GitLab projects 😄

**Comment by dataflake** [comment]
Version 6.3 is now live
