### ISSUE TITLE
Support implicit namespaces

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.testrunner#160]
### What I did:

Converted `megrok.strictrequire` to a package using a PEP 420 implicit namespace.
See https://github.com/zopefoundation/megrok.strictrequire/pull/8

### What I expect to happen:

Tests run like before.

### What actually happened:

No tests were run because directories without an `__init__.py` are not considered to contain Python code.
See https://github.com/zopefoundation/zope.testrunner/blob/4f9048acb7f54677e6e6890b8491e069d136a2d6/src/zope/testrunner/find.py#L295-L299

### What version of Python and Zope/Addons I am using:

- OS independent
- Python 3.7+

⚠️ This feature is required to solve https://github.com/zopefoundation/meta/issues/194

**Comment by dataflake** [comment]
Not sure if it helps, but if you invoke the test runner and pass a specific package name, like `megrok.strictrequire`, the test search will not start in `src`, but in `src/megrok/strictrequire` and circumvent the issue. The tests are found and run.

```
zope-testrunner --test-path=src --package megrok.strictrequire
```

**Comment by icemac** [comment]
@dataflake That's an interesting workaround for running the tests of a single package. The question would be if this could also work when testing an application having multiple packages.

**Comment by dataflake** [comment]
The `package` argument can be passed multiple times.

**Comment by jensens** [comment]
I stumbled over this too some weeks ago and switched to pytest in my project, forgot to create an issue here... Sorry.
