### ISSUE TITLE
Tests are broken on Python 3.13a6+

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.testrunner#167]
See https://github.com/zopefoundation/zope.testrunner/actions/runs/8772493667/job/24071512954

It looks like some changes in GC. And the doctests look like a pain to fix.

**Comment by tseaver** [comment]
I haven't got the gumption to fix doctests which try to interact with the Python `pdb` prompt, especially as it changes over time.  Someone with "doctext fixer"-fu (I can't even recall what they are called these days, but @jimfulton was the only person I knew who could wrangle them well) would have to dive in.

Absent such an expert, my vote would be (in order of preference):
- Remove the failing `edge-case` doctests (and supporting code).
- Skip them for Python >= 3.13.

The `GC` output changes *might* be more manageable, but.... really, its the same problem.
