### ISSUE TITLE
get rid of unittest2 dependency

### ISSUE THREAD

**Issue by agroszer** [zopefoundation/zope.testrunner#22]
because it makes winbot fail with:

```
error: Setup script exited with error: Setup script exited with error: SandboxViolation: open('build\\bdist.win32\\egg\\pip\\_vendor\\requests\\packages\\urllib3\\packages\\ssl_match_hostname\\_implementation.py', 'wb') {}
```

**Comment by agroszer** [comment]
see:
http://winbot.zope.org/builders/zope.testrunner_py_265_32/builds/1534/steps/buildout/logs/stdio

**Comment by tseaver** [comment]
Dropping `unittest2` would mean that the "skip" / "expected failure" stuff would not work on Python 2.6.

Can we try updating the version of `setuptools` installed on the winbot?  I don't see a sandbox violation when I run the tests locally with `tox -e py26`, nor when I run buildout with Python 2.6.  Another alternative would be to have winbot do the tests with Python 2.7.

**Comment by mgedmin** [comment]
This is weird.  Why is it creating files under "pip/_vendor"?  It's as if easy_installing unittest2 is trying to install pip as well, but unittest2's [setup.py](https://hg.python.org/unittest2/file/8928fb47c3a9/setup.py) doesn't look to be doing anything weird.

I'll try to take a look at this.

**Comment by mgedmin** [comment]
The same error affects 5 more packages:
- [z3c.macro](http://winbot.zope.org/builders/z3c.macro_py_265_32/builds/938/steps/buildout/logs/stdio)
- [z3c.pagelet](http://winbot.zope.org/builders/z3c.pagelet_py_265_32/builds/941/steps/buildout/logs/stdio)
- [z3c.ptcompat](http://winbot.zope.org/builders/z3c.ptcompat_py_265_32/builds/1530/steps/buildout/logs/stdio)
- [zope.i18n](http://winbot.zope.org/builders/zope.i18n_py_265_32/builds/1531/steps/buildout/logs/stdio)
- [zope.pagetemplate](http://winbot.zope.org/builders/zope.pagetemplate_py_265_32/builds/1539/steps/buildout/logs/stdio)

**Comment by tseaver** [comment]
Aren't those other failures all because those projects use `zope.testrunner`.

**Comment by agroszer** [comment]
I think too, those others don't have unittest2 as a direct dep

**Comment by mgedmin** [comment]
I'm having trouble reproducing this: my Rackspace Cloud Windows VM with Python 2.6 is [unable to download stuff from PyPI](https://gist.github.com/mgedmin/7637559).

I'm also in favor of switching to Python 2.7 for testing stuff on winbot.  (Python 2.6 was end-of-lifed in 2013, apparently!)

**Comment by mgedmin** [comment]
Tried to spend some quality time on this today -- rdesktop to winbot lags unusably.

How about we nuke winbot from orbit and create a new Windows build infrastructure?  Maybe based on Appveyor or something?

**Comment by mgedmin** [comment]
winbot is a bit faster this morning.

I failed to reproduce this error but got a different (also amusing) one: https://gist.github.com/anonymous/4f3631e0ed119a0876d9

It's the output of bin/buildout -vvv, so we can at least see what it's trying to do.

**Comment by mgedmin** [comment]
Reproduced the failure with bin/buildout -vvv!  https://gist.github.com/anonymous/98a73f4636ebb0cc5ef4

**Comment by mgedmin** [comment]
I suspect that the problem is the same: a filename that is too long, only it somehow gets intercepted and converted into a SandboxViolation.  I have zero evidence to support my theory :)

**Comment by mgedmin** [comment]
BTW the error happens during `pbr-0.10.8/setup.py bdist_egg`, so I'm inclined to file a [pbr](https://pypi.python.org/pypi/pbr) bug.  Only I can't for the life of me find their bug tracker!

**Comment by mgedmin** [comment]
I've filed https://bugs.launchpad.net/pbr/+bug/1437187

**Comment by agroszer** [comment]
quick notes:
- max filename length is 255 on windows AFAIK, the filename in the 76d9 gist comes pretty close
- Appveyor: mmmm maybe, but it will take quite some work and pollute our sources with some files: https://packaging.python.org/en/latest/appveyor.html

simplest/fastest way seems to be to switch winbot tests to py2.7

**Comment by mgedmin** [comment]
Ideas for a workaround: if we require pbr in zope.testrunner[test], on python2.6, then setup_requires won't have to keep installing it into deeper and deeper nested subdirectories and perhaps the tests will pass?

**Comment by mgedmin** [comment]
Maybe we could get unittest2 to drop the setup_requires on traceback2?  https://code.google.com/p/unittest-ext/issues/detail?id=95

**Comment by mgedmin** [comment]
Another possible workaround for winbot would be to wrap the buildout with a virtualenv that has pbr installed.

I tested this manually on winbot:
```
$ virtualenv -p /c/python26_32/python py26
$ py26/scripts/python bootstrap.py
$ bin/buildout # fails
$ py26/scripts/pip install pbr
$ bin/buildout # succeeds
```

**Comment by mgedmin** [comment]
The builds are working again.  Does anyone know why?  I don't see any new releases for unittest2/traceback2/pbr on PyPI, and buildbot indicates we're still using Python 2.6.

**Comment by mgedmin** [comment]
Heh.  I guess a side effect of my workaround experiments created a `unittest2` egg in the shared egg cache (d:/eggs), and that's why the builds are succeeding now.

They will continue to succeed until a new unittest2 version shows up on PyPI, and then we'll have to deal with this again.
