### ISSUE TITLE
Warn about using ZopeTestCase

### ISSUE THREAD

**Issue by gforcada** [zopefoundation/zope.testrunner#34]
@do3cc did an amazing job this last week to spot why Plone tests fail when [bumping zope.testrunner from 4.4.4 to 4.4.10](https://github.com/plone/buildout.coredev/pull/155): mixing ZopeTestCase based tests and plone.app.testing ones makes both step in each others stacks, thus breaking the setup/teardown contract.

As ZopeTestCase is way more old, it would be handy to have a debug mode that lists all tests that a layer based on ZopeTestCase.

Would a pull request that goes in that direction be accepted?

**Comment by tseaver** [comment]
`zope.testrunner` cannot depend on any Zope2 stuff, so any such check would need to be conditional on a "soft" import.  Something like:

```python
try:  # if Zope2 around
    from Testing.ZopeTestCase import ZopeTestCase
except ImportError:
    class ZopeTestCase(object): pass  # dummy, never match
```

In reality, such a feature probably belongs at the higher level (e.g., `plone.app.testing`.

**Comment by jamadden** [comment]
Now that zope.testrunner [enables DeprecationWarning by default](zopefoundation/zope.testrunner#54), maybe this can be solved by having `ZopeTestCase` issue that warning.

**Comment by icemac** [comment]
@gforcada I did not find any notice that `ZopeTestCase` is deprecated, neither in its code nor in the Zope documentation. If it does not play well with `plone.app.testing`, then `plone.app.testing` should check itself for tests mixing things up. `zope.testrunner` does not dependent on Zope2 and it should not depend on it in the future.

I am going to close this issue as there seems to be consensus that a solution for the described problem should not be done here.
