### ISSUE TITLE
Test failure on Python3.4

### ISSUE THREAD

**Issue by domenkozar** [zopefoundation/zope.testrunner#35]
When upgrading wheel/setuptools/pip, following test failure happens:

```
File "/nix/store/0imhpb40v7k9kvgx0adg6hihw8c6aw7l-python3.4-zope.testrunner-4.4.10/lib/python3.4/site-packages/zope/testrunner/tests/testrunner-test-selection.txt", line 236, in testrunner-test-selection.txt
Failed example:
    testrunner.run_internal(defaults)
Expected:
    Running tests at level 1
    Running zope.testrunner.layer.UnitTests tests:
      Set up zope.testrunner.layer.UnitTests in N.NNN seconds.
      Running:
     test_y0 (sample1.sampletests.test1.TestA)
     test_x0 (sample1.sampletests.test1.TestB)
     test_x0 (sample1.sampletests.test1)
     test_y0 (sample1.sampletests.test1)
     test_y0 (sample1.sampletests.test_one.TestA)
     test_x0 (sample1.sampletests.test_one.TestB)
     test_x0 (sample1.sampletests.test_one)
     test_y0 (sample1.sampletests.test_one)
      Ran 8 tests with 0 failures, 0 errors and 0 skipped in N.NNN seconds.
    Tearing down left over layers:
      Tear down zope.testrunner.layer.UnitTests in N.NNN seconds.
    False
Got:
    Running tests at level 1
    Running zope.testrunner.layer.UnitTests tests:
      Set up zope.testrunner.layer.UnitTests in N.NNN seconds.
      Running:
     test_y0 (sample1.sampletests.test1.TestA)
     test_x0 (sample1.sampletests.test1.TestB)
     test_x0 (sample1.sampletests.test1)
     test_y0 (sample1.sampletests.test1)
     testrunner-ex/sample1/sampletests/../../sampletests.txt
     test_y0 (sample1.sampletests.test_one.TestA)
     test_x0 (sample1.sampletests.test_one.TestB)
     test_x0 (sample1.sampletests.test_one)
     test_y0 (sample1.sampletests.test_one)
     testrunner-ex/sample1/sampletests/../../sampletests.txt
      Ran 10 tests with 0 failures, 0 errors and 0 skipped in N.NNN seconds.
    Tearing down left over layers:
      Tear down zope.testrunner.layer.UnitTests in N.NNN seconds.
    False

  Ran 53 tests with 1 failures, 0 errors, 0 skipped in 20.575 seconds.
```

Full log: https://headcounter.org/hydra/build/920121/nixlog/1/raw

**Comment by mgedmin** [comment]
Does this happen every time, or only sometimes?

Any ideas why this doesn't show up on [our Travis tests](https://travis-ci.org/zopefoundation/zope.testrunner/jobs/90252854), or when I'm running `detox` locally?

**Comment by domenkozar** [comment]
My guess is, pip is not 8.0+ https://travis-ci.org/zopefoundation/zope.testrunner/jobs/107953369#L88

**Comment by mgedmin** [comment]
I'm now testing with
```
pip install -U tox detox pip virtualenv setuptools
tox -r
```

and I don't get a failure for Python 3.4.

(I did get one strange failure during virtualenv creation for 2.7: https://dpaste.de/t6qm, but that's not related to this bug.)

**Comment by domenkozar** [comment]
Hmm, upgrading dependencies fixed the issue.

**Comment by mgedmin** [comment]
That's very interesting.  I'd love to get to the bottom of this, but I understand if you don't have the time.

**Comment by orivej** [comment]
This issue still happens from time to time, now with Python 3.6 and zope.testrunner 4.7.0:
https://hydra.nixos.org/job/nixpkgs/staging/python36Packages.zope_testrunner.x86_64-linux/all
With Python 2.7 too: https://hydra.nixos.org/job/nixpkgs/staging/python27Packages.zope_testrunner.x86_64-linux/all
(See the logs of the builds with the red crosses.)

**Comment by mgedmin** [comment]
Oh dear, I know why this happens.

This particular test assertion checks test filtering by `-t regexp`.  The way `-t` is implemented, we apply the regexp to `str(test_case)`.  The `test_case` is a `doctest.DocFileCase()` instance.  The `__str__` of a `DocFileCase()` returns the absolute path of the test filename.

This particular test assertion uses `-tx0 -ty0`.  You have an **x0** in /nix/store/0imhpb40v7k9kvg**x0**... in the original bug description, and a **y0** in /nix/store/pvpbqnd6bsxz4gxr**y0**... in https://hydra.nixos.org/build/62227683/nixlog/2.

**Comment by domenkozar** [comment]
Wow, nice find! :)

**Comment by mgedmin** [comment]
A quick workaround would be to adjust the test to use `-t_x0 -t_y0`.

A  better fix would be to make test filtering to ignore parent directory names.  This is harder:
- we'd have to do `isinstance()` checks to recognize DocFileCase instances
- we no longer know the module-relative pathname passed to DocFileSuite, nor which module it was relative to; so at most we could do an `os.path.relpath()`, which is actually perhaps even better
- should the filtering be relative to the current working directory, or the --test-path passed to the test runner
- should we update `--list-tests` output to show the path we would be filtering against?  I think yes
- should we update regular doctest failure outputs to show the path we would be filtering against?  I'd like to, if possible (although this might require us to modify the private _dt_filename attribute of a DocTest instance, which itself is kept in a private _dt_test attribute on a DocFileCase instance).

**Comment by mgedmin** [comment]
We could, of course, do both: fix it now to remove NixOS pain, then do it nicely.

(I always hated the long absolute pathnames in docfile failures.)

**Comment by mgedmin** [comment]
> We could, of course, do both: fix it now to remove NixOS pain, then do it nicely.

This was a subtle way of saying "I will approve a PR that changes `-tx0 -ty0` to `-t_x0 -t_y0`".

(I'm currently hungry and disinclined to prepare a PR myself.)

**Comment by mgedmin** [comment]
> (I'm currently hungry and disinclined to prepare a PR myself.)

Why do I always manage to shame myself into doing something I had no plans of doing?  See #66.

**Comment by icemac** [comment]
#66 implemented the workaround for this issue. Are there still plans to implement the "better fix" suggested by @mgedmin or should we close this issue resp. make a new one for the "better fix"?

**Comment by mgedmin** [comment]
I've plans, but the plans are very low priority and have no specific time frame.  At some point within the next 10 years I might do this.  Or not.

Let's close this issue for now.
