### ISSUE TITLE
-x/--stop-on-error continues with testing other layers

### ISSUE THREAD

**Issue by niels-bom-md** [zopefoundation/zope.testrunner#37]
I'm creating an issue without an accompanying pull request here because this may be a feature not a bug.

The `-x/--stop-on-error` flag has as the description "stop on first error or failure". When a test suite has multiple layers and this flag is passed the test suite will stop running tests **for that layer**, but not for all layers, which is what I expect, given that description.

Am I overlooking something?
Is this an actual bug to be fixed?
Is this feature imprecisely described?

**Comment by tseaver** [comment]
IMO this behavior is a bug.

**Comment by niels-bom-md** [comment]
I'll try and fix it then.

**Comment by niels-bom-md** [comment]
Question about the Zope header in the Python modules: should I change the copyright year from 2013 to 2016?

**Comment by tseaver** [comment]
> Should I change the copyright year from 2013 to 2016?

Normally no:  the header should reflect the date of creation of the file.  If your patch adds lines that make up a significant percentage of the total lines in the module, then you might consider updating the header to show `2013, 2016`.

**Comment by niels-bom-md** [comment]
I added some Python files, will change the copyright header of those to 2016 then.

**Comment by niels-bom-md** [comment]
The PR for this has been merged, thanks @tseaver .
How does releasing for work this project? I'd like to use the fix :-)

**Comment by mgedmin** [comment]
The way releases work is:
- someone like you asks for a release in a comment on a fixed bug or wherever
- someone like me who has GitHub and PyPI access reviews the changes since last release and runs `fullrelease` from [zest.releaser](https://pypi.python.org/pypi/zest.releaser)
- here you are: https://pypi.python.org/pypi/zope.testrunner/4.5.0

**Comment by niels-bom-md** [comment]
Perfect! Thanks a bunch!
