### ISSUE TITLE
Spurious test failure on slow machines

### ISSUE THREAD

**Issue by jamesjer** [zopefoundation/zope.testrunner#39]
Greetings.  I recently packaged zope.testrunner for the Fedora Linux distribution.  Fedora supports 3 primary architectures: x86_64, i686, and ARM.  We run zope.testrunner's own test suite as part of the build process.  The tests all pass on all 3 architectures, but the ARM builders always report a test failure, because this line is expected:

Total: 321 tests, 0 failures, 0 errors and 0 skipped in N.NNN seconds.

but this is what is actually produced:

Total: 321 tests, 0 failures, 0 errors and 0 skipped in 2 minutes N.NNN seconds.

Is there any way to make the "N minutes" phrase optional on that line?

**Comment by mgedmin** [comment]
[src/zope/testrunner/tests/test_doctest.py](https://github.com/zopefoundation/zope.testrunner/blob/master/src/zope/testrunner/tests/test_doctest.py) has a list of search-replace regexps that try to remove useless differences from the output.  Changing

```python
        (re.compile(r'\d+[.]\d\d\d seconds'), 'N.NNN seconds'),
```
to
```python
        (re.compile(r'(\d+ minutes )?\d+[.]\d\d\d seconds'), 'N.NNN seconds'),
```
in both places ought to do the trick.

**Comment by mgedmin** [comment]
It would be awesome if you could verify whether 825bbed fixes the issue for you.

**Comment by tseaver** [comment]
@mgedmin I don't see a pull request for that change -- are you waiting for a reply from @jamesjer before opening one?

**Comment by jamesjer** [comment]
Thank you @mgedmin , that does fix the issue for me.

**Comment by mgedmin** [comment]
I think I simply forgot to create a PR after pushing the branch.

**Comment by mgedmin** [comment]
@jamesjer please mention if a new release on PyPI would make your life easier!

**Comment by jamesjer** [comment]
From my point of view, there is no need for an immediate release to address the issue.  I applied your patch to the Fedora build, so we're good for now until you have some other reason to make a release.  Thank you for the quick action.
