### ISSUE TITLE
Running tests should enable DeprecationWarning, etc

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/zope.testrunner#54]
[According to Nick Coghlan](https://mail.python.org/pipermail/python-dev/2017-November/150436.html), test runners are expected to override the default filters and enable the same warnings that [unittest test runners do](https://docs.python.org/3/library/unittest.html#unittest.TextTestRunner)

See also the pytest issue: https://github.com/pytest-dev/pytest/issues/2908

**Comment by mgedmin** [comment]
What `unittest` does is this (simplified):

```python
import warnings

with warnings.catch_warnings():
    if not sys.warnoptions:
        warnings.simplefilter('default')
        warnings.filterwarnings('module', category=DeprecationWarning,
                                message=r'Please use assert\w+ instead.')
    # run the entire test suite
```

**Comment by jamadden** [comment]
I'm working on the PR 😄

**Comment by mgedmin** [comment]
> I'm working on the PR ￼

I was trying to find you on IRC or Twitter to ask out of band if you intended to work on a PR, without cluttering the GitHub issue.  ;-)

**Comment by mgedmin** [comment]
@jamadden: I gave you PyPI access to zope.testrunner.
