### ISSUE TITLE
"zope.testrunner" can crash due to "https://bugs.python.org/issue35283"

### ISSUE THREAD

**Issue by d-maurer** [zopefoundation/zope.testrunner#81]
"zope.testrunner.runner.TestResult.stopTest" uses the thread method "isAlive". Due to "https://bugs.python.org/issue35283", this causes the runner to die with an "AssertionError" when it happens to be called on a "_DummyThread".

"_DummyThread" instances are internally created by Python's "threading" module. When I have understood the explanation in the "threading" comments correctly,  this happens when a thread started with "_thread.start_new_thread" calls (maybe indirectly) "threading.current_thread".

I recommend to consistently replace the use of "threading.Thread.isAlive" by the PEP 8 conformant "threading.Thread.is_alive" to work around the above Python bug.

**Comment by mgedmin** [comment]
:+1:

BTW which Python versions are affected by this?

**Comment by d-maurer** [comment]
> BTW which Python versions are affected by this?
I have observed the bug in Python 3.6. It is still there in the "master" branch of Python's "git" repository on "github" (targeting Python 3.8).

The current "zope.testrunner" (4.9) is using "argparse". This is part of Python since 3.2. Therefore, I have not checked for Pyhton 2 (as I have assumed that this version will require Python >= 3.2 anyway).

**Comment by d-maurer** [comment]
> Python 2.7 has argparse ;)

Python2.7's "threading.Thread" defines a native "isAlive" and sets "is_alive" as an alias. Its "_DummyThread" overrides neither of these methods. Thus, the bug (likely) does not exist in Python2.7.

**Comment by mgedmin** [comment]
Fixed in zope.testrunner 4.9.1.
