### ISSUE TITLE
Shut down outdated documentation

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/zope.testrunner#92]
**outdated documentation**
https://docs.zope.org/zope.testrunner/index.html

**current documentation**
https://zopetestrunner.readthedocs.io/en/latest/

Please shut down https://docs.zope.org/zope.testrunner/index.html to avoid confusion.

**Comment by jugmac00** [comment]
@dataflake Have you removed the documentation from docs.zope.org? Well, I guess so, as afaik you removed all content from docs.zope.org and setup a "catchall" redirection to www.zope.org.

Please close the ticket if I that's the case.

**Comment by dataflake** [comment]
Thanks for the @ mention, otherwise I would never have seen this ticket. If there are other tickets in other zopefoundation packages related to this please either assign me or mention me.
